development:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcpostgresql' : 'postgresql' %>
  database: railsjam
  username: railsjam
  password: railsjam

production:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcpostgresql' : 'postgresql' %>
  database: railsjam
  username: railsjam
  password: railsjam


