development:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcmysql' : 'mysql' %>
  encoding: utf8
  database: sample_dev
  username: sample
  password: p1x1s

production:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcmysql' : 'mysql' %>
  encoding: utf8
  database: sample_prod
  username: sample
  password: p1x1s


